AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hydrogen-stats

  Tracker for Hydrogen stats

Globals:
  Function:
    AutoPublishAlias: live
    Tracing: Active
    Environment:
      Variables:
        DEAD_LETTER_TOPIC: !Ref HydrogenStatsSnsTopic
        DATA_BUCKET: stats.hydrogendefi.xyz.data
    DeadLetterQueue:
      Type: SNS
      TargetArn: !Ref HydrogenStatsSnsTopic

Resources:
  # Rest API
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: HydrogenStatsApi
      Domain:
        DomainName: stats.hydrogendefi.xyz
        CertificateArn: arn:aws:acm:us-west-2:776862011846:certificate/57a67298-28b4-4c50-9cc4-3470934796fa
        Route53:
          HostedZoneId: Z0806338NRYLUT7WSH5Q
      StageName: prod
      TracingEnabled: true
  OptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HydrogenStatsOptionsFunction
      Handler: api/options.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: options
            RestApiId: !Ref RestApi
  FaviconFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HydrogenStatsFaviconFunction
      Handler: api/favicon/get.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /favicon.ico
            Method: get
            RestApiId: !Ref RestApi
  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HydrogenStatsIndexFunction
      Handler: api/get.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref RestApi
  TrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HydrogenStatsTrackerFunction
      Handler: api/tracker/tracker.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(60 minutes)
  StateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HydrogenStatsStateFunction
      Handler: api/state/get.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /state
            Method: get
            RestApiId: !Ref RestApi
  EventsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HydrogenStatsEventsFunction
      Handler: api/events/get.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /events
            Method: get
            RestApiId: !Ref RestApi
  PoolMetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HydrogenStatsPoolMetadataFunction
      Handler: api/pools/metadata/get.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /pools/metadata
            Method: get
            RestApiId: !Ref RestApi
  ContractUriFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HydrogenStatsContractUriFunction
      Handler: api/contract_uri/get.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /contract_uri
            Method: get
            RestApiId: !Ref RestApi
  DeprecationNoticeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HydrogenStatsDeprecationNoticeFunction
      Handler: api/deprecation_notice/get.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 900
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /deprecation_notice
            Method: get
            RestApiId: !Ref RestApi
  # lambda execution role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HydrogenStatsLambdaExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: HydrogenStatsLambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sns:Publish"
                Resource: !Ref HydrogenStatsSnsTopic
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                  - "s3:ListBucket"
                  - "s3:PutObject"
                  - "s3:ReplicateObject"
                  - "s3:RestoreObject"
                Resource:
                  - "arn:aws:s3:::stats.hydrogendefi.xyz.data"
                  - "arn:aws:s3:::stats.hydrogendefi.xyz.data/*"
                  - "arn:aws:s3:::stats-cdn.hydrogendefi.xyz"
                  - "arn:aws:s3:::stats-cdn.hydrogendefi.xyz/*"
                  - "arn:aws:s3:::assets.hydrogendefi.xyz"
                  - "arn:aws:s3:::assets.hydrogendefi.xyz/*"
  # Data Bucket
  HydrogenStatsDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stats.hydrogendefi.xyz.data
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - HEAD
              - GET
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
  # begin stats-cdn.hydrogendefi.xyz bucket and distribution
  HydrogenStatsCdnDataWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stats-cdn.hydrogendefi.xyz
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - HEAD
              - GET
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
      WebsiteConfiguration:
        IndexDocument: index.html
      Tags:
        - Key: Project
          Value: client
  HydrogenStatsCdnDataWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref HydrogenStatsCdnDataWebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action:
            - "s3:GetObject"
          Effect: "Allow"
          Resource: arn:aws:s3:::stats-cdn.hydrogendefi.xyz/*
          Principal:
            AWS: !Join ["", ["arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ", "ENZYGQ4CE2XJG"] ]
  HydrogenStatsCdnDataWebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: HydrogenStatsCdnDataWebsiteBucket
            DomainName: stats-cdn.hydrogendefi.xyz.s3.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: !Join ["", ["origin-access-identity/cloudfront/", "ENZYGQ4CE2XJG"] ]
        Enabled: 'true'
        Aliases:
          - stats-cdn.hydrogendefi.xyz
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: HydrogenStatsCdnDataWebsiteBucket
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad"
          OriginRequestPolicyId: "88a5eaf4-2fd4-4709-b370-b4c650ea3fcf"
          ResponseHeadersPolicyId: "5cc3b908-e619-4b99-88e5-2cf7f45965bd"
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:776862011846:certificate/114d2743-9bb1-4391-adc5-3178d37c8b68
          MinimumProtocolVersion: TLSv1.2_2018
          SslSupportMethod: sni-only
        HttpVersion: http2
        IPV6Enabled: true
      Tags:
        - Key: Project
          Value: client
    DependsOn: HydrogenStatsCdnDataWebsiteBucketPolicy
  HydrogenStatsCdnDataDnsZoneIPv4:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt HydrogenStatsCdnDataWebsiteDistribution.DomainName
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: hydrogendefi.xyz.
      Name: stats-cdn.hydrogendefi.xyz
      Type: A
    DependsOn: HydrogenStatsCdnDataWebsiteDistribution
  HydrogenStatsCdnDataDnsZoneIPv6:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt HydrogenStatsCdnDataWebsiteDistribution.DomainName
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: hydrogendefi.xyz.
      Name: stats-cdn.hydrogendefi.xyz
      Type: AAAA
    DependsOn: HydrogenStatsCdnDataWebsiteDistribution
  # end stats-cdn.hydrogendefi.xyz bucket and distribution
  HydrogenStatsSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "Hydrogen Stats SNS Topic"
      TopicName: "HydrogenStatsSnsTopic"
